window.USERS = [
  {
    id: 1,
    departamento: "Lima",
    provincia: "Lima",
    distrito: "Lima",
    nombres: "Juan",
    ape_materno: "Pérez",
    ape_paterno: "Gómez",
    dni: "12345678",
    telefono: "987654321",
    direccion: "Av. Principal 123",
    nacimiento: "1990-01-01",
    nombreCargo: "Gerente",
    nombreContrato: "Tiempo completo",
    fechaContrato: "2023-01-01",
    turno: "Mañana",
    tipoUsuario: "Administrador",
    correo: "juan.perez@example.com",
    clave: "132456",
    estado: "1",
  },
];
